spring:
  application:
    name: spring.ai
  ai:
    vertex:
      ai:
        gemini:
          projectId: gen-lang-client-0064138747
          location: asia-southeast1
          
gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=
    key: AIzaSyD6EDIlDq76kwZibOw9-xxeqanA9z8gpts

server:
  port: 10001